export declare class NoErrorThrownError extends Error {
}
/**
 * a method which returns the error thrown from executing the logic passed into it
 *
 * usecases
 * - testing that a some logic throws an error
 *
 * note
 * - uses type overloading, so if you pass in a promise or async function, you'll be given a promise; otherwise, sync
 */
export declare function getError<T = Error>(from: () => Promise<unknown>): Promise<T | NoErrorThrownError>;
export declare function getError<T = Error>(from: Promise<unknown>): Promise<T | NoErrorThrownError>;
export declare function getError<T = Error>(from: () => unknown): T | NoErrorThrownError;
