"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const UnexpectedCodePathError_1 = require("./UnexpectedCodePathError");
const getError_1 = require("./getError");
describe('UnexpectedCodePathError', () => {
    it('should produce a helpful, observable error message', () => {
        const error = new UnexpectedCodePathError_1.UnexpectedCodePathError('no tires on the vehicle', {
            tires: [],
        });
        expect(error).toMatchSnapshot();
    });
    it('should be throwable in a ternary conveniently and precisely', () => {
        const error = (0, getError_1.getError)(() => {
            var _a, _b;
            // this case should not throw
            const customerOne = {
                phone: 'yes',
            };
            const phoneOne = (_a = customerOne.phone) !== null && _a !== void 0 ? _a : UnexpectedCodePathError_1.UnexpectedCodePathError.throw('phone one not found!');
            // but this case should throw
            const customerTwo = {
                phone: null,
            };
            const phoneTwo = (_b = customerTwo.phone) !== null && _b !== void 0 ? _b : UnexpectedCodePathError_1.UnexpectedCodePathError.throw('phone two not found!');
        });
        expect(error).toBeInstanceOf(UnexpectedCodePathError_1.UnexpectedCodePathError);
        expect(error.message).toContain('phone two not found!');
    });
});
//# sourceMappingURL=UnexpectedCodePathError.test.js.map